name: Lint and test

on:
  push:

jobs:

  isort:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check imports order
      run: ./scripts/check_isort
