name: Lint and test

on:
  push:

jobs:

  isort:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - /__w/python-amazon-paapi/python-amazon-paapi:/code
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check imports order
      run: ls -la && ./scripts/check_isort
