name: Lint and test

on:
  push:

permissions:
  pull-requests: read

jobs:

  isort:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - ${{github.workspace}}:/code
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Check imports order
      run: ./scripts/check_isort

  black:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - ${{github.workspace}}:/code
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Check code format
      run: ./scripts/check_black

  flake8:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - ${{github.workspace}}:/code
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Check code errors
      run: ./scripts/check_flake8

  pylint:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - ${{github.workspace}}:/code
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Check code errors
      run: ./scripts/check_pylint

  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check code errors
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
