name: Lint and test

on:
  push:

jobs:

  isort:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - /code:/volume_mount
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check imports order
      run: ./scripts/check_isort
