name: Lint and test

on:
  push:

env:
  REPO_PATH: "/__w/python-amazon-paapi/python-amazon-paapi"

jobs:

  isort:
    runs-on: ubuntu-latest
    container:
      image: sergioteula/pytools
      volumes:
        - ${{github.workspace}}:/code
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check imports order
      run: ./scripts/check_isort
